# 
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 provide.io llc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pyvider.protocols.tfprotov6.protobuf import tfplugin6_pb2 as tfplugin6__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tfplugin6_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProviderStub:
    """////// Information about what a provider supports/expects
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetadata = channel.unary_unary(
                '/tfplugin6.Provider/GetMetadata',
                request_serializer=tfplugin6__pb2.GetMetadata.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.GetMetadata.Response.FromString,
                _registered_method=True)
        self.GetProviderSchema = channel.unary_unary(
                '/tfplugin6.Provider/GetProviderSchema',
                request_serializer=tfplugin6__pb2.GetProviderSchema.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.GetProviderSchema.Response.FromString,
                _registered_method=True)
        self.ValidateProviderConfig = channel.unary_unary(
                '/tfplugin6.Provider/ValidateProviderConfig',
                request_serializer=tfplugin6__pb2.ValidateProviderConfig.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ValidateProviderConfig.Response.FromString,
                _registered_method=True)
        self.ValidateResourceConfig = channel.unary_unary(
                '/tfplugin6.Provider/ValidateResourceConfig',
                request_serializer=tfplugin6__pb2.ValidateResourceConfig.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ValidateResourceConfig.Response.FromString,
                _registered_method=True)
        self.ValidateDataResourceConfig = channel.unary_unary(
                '/tfplugin6.Provider/ValidateDataResourceConfig',
                request_serializer=tfplugin6__pb2.ValidateDataResourceConfig.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ValidateDataResourceConfig.Response.FromString,
                _registered_method=True)
        self.UpgradeResourceState = channel.unary_unary(
                '/tfplugin6.Provider/UpgradeResourceState',
                request_serializer=tfplugin6__pb2.UpgradeResourceState.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.UpgradeResourceState.Response.FromString,
                _registered_method=True)
        self.GetResourceIdentitySchemas = channel.unary_unary(
                '/tfplugin6.Provider/GetResourceIdentitySchemas',
                request_serializer=tfplugin6__pb2.GetResourceIdentitySchemas.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.GetResourceIdentitySchemas.Response.FromString,
                _registered_method=True)
        self.UpgradeResourceIdentity = channel.unary_unary(
                '/tfplugin6.Provider/UpgradeResourceIdentity',
                request_serializer=tfplugin6__pb2.UpgradeResourceIdentity.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.UpgradeResourceIdentity.Response.FromString,
                _registered_method=True)
        self.ConfigureProvider = channel.unary_unary(
                '/tfplugin6.Provider/ConfigureProvider',
                request_serializer=tfplugin6__pb2.ConfigureProvider.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ConfigureProvider.Response.FromString,
                _registered_method=True)
        self.ReadResource = channel.unary_unary(
                '/tfplugin6.Provider/ReadResource',
                request_serializer=tfplugin6__pb2.ReadResource.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ReadResource.Response.FromString,
                _registered_method=True)
        self.PlanResourceChange = channel.unary_unary(
                '/tfplugin6.Provider/PlanResourceChange',
                request_serializer=tfplugin6__pb2.PlanResourceChange.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.PlanResourceChange.Response.FromString,
                _registered_method=True)
        self.ApplyResourceChange = channel.unary_unary(
                '/tfplugin6.Provider/ApplyResourceChange',
                request_serializer=tfplugin6__pb2.ApplyResourceChange.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ApplyResourceChange.Response.FromString,
                _registered_method=True)
        self.ImportResourceState = channel.unary_unary(
                '/tfplugin6.Provider/ImportResourceState',
                request_serializer=tfplugin6__pb2.ImportResourceState.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ImportResourceState.Response.FromString,
                _registered_method=True)
        self.MoveResourceState = channel.unary_unary(
                '/tfplugin6.Provider/MoveResourceState',
                request_serializer=tfplugin6__pb2.MoveResourceState.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.MoveResourceState.Response.FromString,
                _registered_method=True)
        self.ReadDataSource = channel.unary_unary(
                '/tfplugin6.Provider/ReadDataSource',
                request_serializer=tfplugin6__pb2.ReadDataSource.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ReadDataSource.Response.FromString,
                _registered_method=True)
        self.GenerateResourceConfig = channel.unary_unary(
                '/tfplugin6.Provider/GenerateResourceConfig',
                request_serializer=tfplugin6__pb2.GenerateResourceConfig.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.GenerateResourceConfig.Response.FromString,
                _registered_method=True)
        self.ValidateEphemeralResourceConfig = channel.unary_unary(
                '/tfplugin6.Provider/ValidateEphemeralResourceConfig',
                request_serializer=tfplugin6__pb2.ValidateEphemeralResourceConfig.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ValidateEphemeralResourceConfig.Response.FromString,
                _registered_method=True)
        self.OpenEphemeralResource = channel.unary_unary(
                '/tfplugin6.Provider/OpenEphemeralResource',
                request_serializer=tfplugin6__pb2.OpenEphemeralResource.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.OpenEphemeralResource.Response.FromString,
                _registered_method=True)
        self.RenewEphemeralResource = channel.unary_unary(
                '/tfplugin6.Provider/RenewEphemeralResource',
                request_serializer=tfplugin6__pb2.RenewEphemeralResource.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.RenewEphemeralResource.Response.FromString,
                _registered_method=True)
        self.CloseEphemeralResource = channel.unary_unary(
                '/tfplugin6.Provider/CloseEphemeralResource',
                request_serializer=tfplugin6__pb2.CloseEphemeralResource.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.CloseEphemeralResource.Response.FromString,
                _registered_method=True)
        self.ListResource = channel.unary_stream(
                '/tfplugin6.Provider/ListResource',
                request_serializer=tfplugin6__pb2.ListResource.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ListResource.Event.FromString,
                _registered_method=True)
        self.ValidateListResourceConfig = channel.unary_unary(
                '/tfplugin6.Provider/ValidateListResourceConfig',
                request_serializer=tfplugin6__pb2.ValidateListResourceConfig.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ValidateListResourceConfig.Response.FromString,
                _registered_method=True)
        self.GetFunctions = channel.unary_unary(
                '/tfplugin6.Provider/GetFunctions',
                request_serializer=tfplugin6__pb2.GetFunctions.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.GetFunctions.Response.FromString,
                _registered_method=True)
        self.CallFunction = channel.unary_unary(
                '/tfplugin6.Provider/CallFunction',
                request_serializer=tfplugin6__pb2.CallFunction.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.CallFunction.Response.FromString,
                _registered_method=True)
        self.ValidateStateStoreConfig = channel.unary_unary(
                '/tfplugin6.Provider/ValidateStateStoreConfig',
                request_serializer=tfplugin6__pb2.ValidateStateStore.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ValidateStateStore.Response.FromString,
                _registered_method=True)
        self.ConfigureStateStore = channel.unary_unary(
                '/tfplugin6.Provider/ConfigureStateStore',
                request_serializer=tfplugin6__pb2.ConfigureStateStore.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ConfigureStateStore.Response.FromString,
                _registered_method=True)
        self.ReadStateBytes = channel.unary_stream(
                '/tfplugin6.Provider/ReadStateBytes',
                request_serializer=tfplugin6__pb2.ReadStateBytes.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ReadStateBytes.Response.FromString,
                _registered_method=True)
        self.WriteStateBytes = channel.stream_unary(
                '/tfplugin6.Provider/WriteStateBytes',
                request_serializer=tfplugin6__pb2.WriteStateBytes.RequestChunk.SerializeToString,
                response_deserializer=tfplugin6__pb2.WriteStateBytes.Response.FromString,
                _registered_method=True)
        self.LockState = channel.unary_unary(
                '/tfplugin6.Provider/LockState',
                request_serializer=tfplugin6__pb2.LockState.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.LockState.Response.FromString,
                _registered_method=True)
        self.UnlockState = channel.unary_unary(
                '/tfplugin6.Provider/UnlockState',
                request_serializer=tfplugin6__pb2.UnlockState.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.UnlockState.Response.FromString,
                _registered_method=True)
        self.GetStates = channel.unary_unary(
                '/tfplugin6.Provider/GetStates',
                request_serializer=tfplugin6__pb2.GetStates.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.GetStates.Response.FromString,
                _registered_method=True)
        self.DeleteState = channel.unary_unary(
                '/tfplugin6.Provider/DeleteState',
                request_serializer=tfplugin6__pb2.DeleteState.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.DeleteState.Response.FromString,
                _registered_method=True)
        self.PlanAction = channel.unary_unary(
                '/tfplugin6.Provider/PlanAction',
                request_serializer=tfplugin6__pb2.PlanAction.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.PlanAction.Response.FromString,
                _registered_method=True)
        self.InvokeAction = channel.unary_stream(
                '/tfplugin6.Provider/InvokeAction',
                request_serializer=tfplugin6__pb2.InvokeAction.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.InvokeAction.Event.FromString,
                _registered_method=True)
        self.ValidateActionConfig = channel.unary_unary(
                '/tfplugin6.Provider/ValidateActionConfig',
                request_serializer=tfplugin6__pb2.ValidateActionConfig.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.ValidateActionConfig.Response.FromString,
                _registered_method=True)
        self.StopProvider = channel.unary_unary(
                '/tfplugin6.Provider/StopProvider',
                request_serializer=tfplugin6__pb2.StopProvider.Request.SerializeToString,
                response_deserializer=tfplugin6__pb2.StopProvider.Response.FromString,
                _registered_method=True)


class ProviderServicer:
    """////// Information about what a provider supports/expects
    """

    def GetMetadata(self, request, context):
        """GetMetadata returns upfront information about server capabilities and
        supported resource types without requiring the server to instantiate all
        schema information, which may be memory intensive.
        This method is CURRENTLY UNUSED and it serves mostly for convenience
        of code generation inside of terraform-plugin-mux.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderSchema(self, request, context):
        """GetSchema returns schema information for the provider, data resources,
        and managed resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateProviderConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateResourceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateDataResourceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpgradeResourceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceIdentitySchemas(self, request, context):
        """GetResourceIdentitySchemas returns the identity schemas for all managed
        resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpgradeResourceIdentity(self, request, context):
        """UpgradeResourceIdentityData should return the upgraded resource identity
        data for a managed resource type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureProvider(self, request, context):
        """////// One-time initialization, called before other functions below
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadResource(self, request, context):
        """////// Managed Resource Lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanResourceChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyResourceChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportResourceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveResourceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDataSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateResourceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateEphemeralResourceConfig(self, request, context):
        """////// Ephemeral Resource Lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenEphemeralResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewEphemeralResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseEphemeralResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListResource(self, request, context):
        """///// List
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateListResourceConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFunctions(self, request, context):
        """GetFunctions returns the definitions of all functions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallFunction(self, request, context):
        """////// Provider-contributed Functions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateStateStoreConfig(self, request, context):
        """ValidateStateStoreConfig performs configuration validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureStateStore(self, request, context):
        """ConfigureStateStore configures the state store, such as S3 connection in the context of already configured provider
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadStateBytes(self, request, context):
        """ReadStateBytes streams byte chunks of a given state file from a state store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteStateBytes(self, request_iterator, context):
        """WriteStateBytes streams byte chunks of a given state file into a state store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockState(self, request, context):
        """LockState locks a given state (i.e. CE workspace)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockState(self, request, context):
        """UnlockState unlocks a given state (i.e. CE workspace)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStates(self, request, context):
        """GetStates returns a list of all states (i.e. CE workspaces) managed by a given state store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteState(self, request, context):
        """DeleteState instructs a given state store to delete a specific state (i.e. a CE workspace)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanAction(self, request, context):
        """////// Actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateActionConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopProvider(self, request, context):
        """////// Graceful Shutdown
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=tfplugin6__pb2.GetMetadata.Request.FromString,
                    response_serializer=tfplugin6__pb2.GetMetadata.Response.SerializeToString,
            ),
            'GetProviderSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderSchema,
                    request_deserializer=tfplugin6__pb2.GetProviderSchema.Request.FromString,
                    response_serializer=tfplugin6__pb2.GetProviderSchema.Response.SerializeToString,
            ),
            'ValidateProviderConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateProviderConfig,
                    request_deserializer=tfplugin6__pb2.ValidateProviderConfig.Request.FromString,
                    response_serializer=tfplugin6__pb2.ValidateProviderConfig.Response.SerializeToString,
            ),
            'ValidateResourceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateResourceConfig,
                    request_deserializer=tfplugin6__pb2.ValidateResourceConfig.Request.FromString,
                    response_serializer=tfplugin6__pb2.ValidateResourceConfig.Response.SerializeToString,
            ),
            'ValidateDataResourceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateDataResourceConfig,
                    request_deserializer=tfplugin6__pb2.ValidateDataResourceConfig.Request.FromString,
                    response_serializer=tfplugin6__pb2.ValidateDataResourceConfig.Response.SerializeToString,
            ),
            'UpgradeResourceState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpgradeResourceState,
                    request_deserializer=tfplugin6__pb2.UpgradeResourceState.Request.FromString,
                    response_serializer=tfplugin6__pb2.UpgradeResourceState.Response.SerializeToString,
            ),
            'GetResourceIdentitySchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceIdentitySchemas,
                    request_deserializer=tfplugin6__pb2.GetResourceIdentitySchemas.Request.FromString,
                    response_serializer=tfplugin6__pb2.GetResourceIdentitySchemas.Response.SerializeToString,
            ),
            'UpgradeResourceIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpgradeResourceIdentity,
                    request_deserializer=tfplugin6__pb2.UpgradeResourceIdentity.Request.FromString,
                    response_serializer=tfplugin6__pb2.UpgradeResourceIdentity.Response.SerializeToString,
            ),
            'ConfigureProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureProvider,
                    request_deserializer=tfplugin6__pb2.ConfigureProvider.Request.FromString,
                    response_serializer=tfplugin6__pb2.ConfigureProvider.Response.SerializeToString,
            ),
            'ReadResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadResource,
                    request_deserializer=tfplugin6__pb2.ReadResource.Request.FromString,
                    response_serializer=tfplugin6__pb2.ReadResource.Response.SerializeToString,
            ),
            'PlanResourceChange': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanResourceChange,
                    request_deserializer=tfplugin6__pb2.PlanResourceChange.Request.FromString,
                    response_serializer=tfplugin6__pb2.PlanResourceChange.Response.SerializeToString,
            ),
            'ApplyResourceChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyResourceChange,
                    request_deserializer=tfplugin6__pb2.ApplyResourceChange.Request.FromString,
                    response_serializer=tfplugin6__pb2.ApplyResourceChange.Response.SerializeToString,
            ),
            'ImportResourceState': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportResourceState,
                    request_deserializer=tfplugin6__pb2.ImportResourceState.Request.FromString,
                    response_serializer=tfplugin6__pb2.ImportResourceState.Response.SerializeToString,
            ),
            'MoveResourceState': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveResourceState,
                    request_deserializer=tfplugin6__pb2.MoveResourceState.Request.FromString,
                    response_serializer=tfplugin6__pb2.MoveResourceState.Response.SerializeToString,
            ),
            'ReadDataSource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDataSource,
                    request_deserializer=tfplugin6__pb2.ReadDataSource.Request.FromString,
                    response_serializer=tfplugin6__pb2.ReadDataSource.Response.SerializeToString,
            ),
            'GenerateResourceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateResourceConfig,
                    request_deserializer=tfplugin6__pb2.GenerateResourceConfig.Request.FromString,
                    response_serializer=tfplugin6__pb2.GenerateResourceConfig.Response.SerializeToString,
            ),
            'ValidateEphemeralResourceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateEphemeralResourceConfig,
                    request_deserializer=tfplugin6__pb2.ValidateEphemeralResourceConfig.Request.FromString,
                    response_serializer=tfplugin6__pb2.ValidateEphemeralResourceConfig.Response.SerializeToString,
            ),
            'OpenEphemeralResource': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenEphemeralResource,
                    request_deserializer=tfplugin6__pb2.OpenEphemeralResource.Request.FromString,
                    response_serializer=tfplugin6__pb2.OpenEphemeralResource.Response.SerializeToString,
            ),
            'RenewEphemeralResource': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewEphemeralResource,
                    request_deserializer=tfplugin6__pb2.RenewEphemeralResource.Request.FromString,
                    response_serializer=tfplugin6__pb2.RenewEphemeralResource.Response.SerializeToString,
            ),
            'CloseEphemeralResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseEphemeralResource,
                    request_deserializer=tfplugin6__pb2.CloseEphemeralResource.Request.FromString,
                    response_serializer=tfplugin6__pb2.CloseEphemeralResource.Response.SerializeToString,
            ),
            'ListResource': grpc.unary_stream_rpc_method_handler(
                    servicer.ListResource,
                    request_deserializer=tfplugin6__pb2.ListResource.Request.FromString,
                    response_serializer=tfplugin6__pb2.ListResource.Event.SerializeToString,
            ),
            'ValidateListResourceConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateListResourceConfig,
                    request_deserializer=tfplugin6__pb2.ValidateListResourceConfig.Request.FromString,
                    response_serializer=tfplugin6__pb2.ValidateListResourceConfig.Response.SerializeToString,
            ),
            'GetFunctions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunctions,
                    request_deserializer=tfplugin6__pb2.GetFunctions.Request.FromString,
                    response_serializer=tfplugin6__pb2.GetFunctions.Response.SerializeToString,
            ),
            'CallFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.CallFunction,
                    request_deserializer=tfplugin6__pb2.CallFunction.Request.FromString,
                    response_serializer=tfplugin6__pb2.CallFunction.Response.SerializeToString,
            ),
            'ValidateStateStoreConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateStateStoreConfig,
                    request_deserializer=tfplugin6__pb2.ValidateStateStore.Request.FromString,
                    response_serializer=tfplugin6__pb2.ValidateStateStore.Response.SerializeToString,
            ),
            'ConfigureStateStore': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureStateStore,
                    request_deserializer=tfplugin6__pb2.ConfigureStateStore.Request.FromString,
                    response_serializer=tfplugin6__pb2.ConfigureStateStore.Response.SerializeToString,
            ),
            'ReadStateBytes': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadStateBytes,
                    request_deserializer=tfplugin6__pb2.ReadStateBytes.Request.FromString,
                    response_serializer=tfplugin6__pb2.ReadStateBytes.Response.SerializeToString,
            ),
            'WriteStateBytes': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteStateBytes,
                    request_deserializer=tfplugin6__pb2.WriteStateBytes.RequestChunk.FromString,
                    response_serializer=tfplugin6__pb2.WriteStateBytes.Response.SerializeToString,
            ),
            'LockState': grpc.unary_unary_rpc_method_handler(
                    servicer.LockState,
                    request_deserializer=tfplugin6__pb2.LockState.Request.FromString,
                    response_serializer=tfplugin6__pb2.LockState.Response.SerializeToString,
            ),
            'UnlockState': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockState,
                    request_deserializer=tfplugin6__pb2.UnlockState.Request.FromString,
                    response_serializer=tfplugin6__pb2.UnlockState.Response.SerializeToString,
            ),
            'GetStates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStates,
                    request_deserializer=tfplugin6__pb2.GetStates.Request.FromString,
                    response_serializer=tfplugin6__pb2.GetStates.Response.SerializeToString,
            ),
            'DeleteState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteState,
                    request_deserializer=tfplugin6__pb2.DeleteState.Request.FromString,
                    response_serializer=tfplugin6__pb2.DeleteState.Response.SerializeToString,
            ),
            'PlanAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanAction,
                    request_deserializer=tfplugin6__pb2.PlanAction.Request.FromString,
                    response_serializer=tfplugin6__pb2.PlanAction.Response.SerializeToString,
            ),
            'InvokeAction': grpc.unary_stream_rpc_method_handler(
                    servicer.InvokeAction,
                    request_deserializer=tfplugin6__pb2.InvokeAction.Request.FromString,
                    response_serializer=tfplugin6__pb2.InvokeAction.Event.SerializeToString,
            ),
            'ValidateActionConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateActionConfig,
                    request_deserializer=tfplugin6__pb2.ValidateActionConfig.Request.FromString,
                    response_serializer=tfplugin6__pb2.ValidateActionConfig.Response.SerializeToString,
            ),
            'StopProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.StopProvider,
                    request_deserializer=tfplugin6__pb2.StopProvider.Request.FromString,
                    response_serializer=tfplugin6__pb2.StopProvider.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tfplugin6.Provider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tfplugin6.Provider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Provider:
    """////// Information about what a provider supports/expects
    """

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/GetMetadata',
            tfplugin6__pb2.GetMetadata.Request.SerializeToString,
            tfplugin6__pb2.GetMetadata.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/GetProviderSchema',
            tfplugin6__pb2.GetProviderSchema.Request.SerializeToString,
            tfplugin6__pb2.GetProviderSchema.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateProviderConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ValidateProviderConfig',
            tfplugin6__pb2.ValidateProviderConfig.Request.SerializeToString,
            tfplugin6__pb2.ValidateProviderConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateResourceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ValidateResourceConfig',
            tfplugin6__pb2.ValidateResourceConfig.Request.SerializeToString,
            tfplugin6__pb2.ValidateResourceConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateDataResourceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ValidateDataResourceConfig',
            tfplugin6__pb2.ValidateDataResourceConfig.Request.SerializeToString,
            tfplugin6__pb2.ValidateDataResourceConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpgradeResourceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/UpgradeResourceState',
            tfplugin6__pb2.UpgradeResourceState.Request.SerializeToString,
            tfplugin6__pb2.UpgradeResourceState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceIdentitySchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/GetResourceIdentitySchemas',
            tfplugin6__pb2.GetResourceIdentitySchemas.Request.SerializeToString,
            tfplugin6__pb2.GetResourceIdentitySchemas.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpgradeResourceIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/UpgradeResourceIdentity',
            tfplugin6__pb2.UpgradeResourceIdentity.Request.SerializeToString,
            tfplugin6__pb2.UpgradeResourceIdentity.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ConfigureProvider',
            tfplugin6__pb2.ConfigureProvider.Request.SerializeToString,
            tfplugin6__pb2.ConfigureProvider.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ReadResource',
            tfplugin6__pb2.ReadResource.Request.SerializeToString,
            tfplugin6__pb2.ReadResource.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanResourceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/PlanResourceChange',
            tfplugin6__pb2.PlanResourceChange.Request.SerializeToString,
            tfplugin6__pb2.PlanResourceChange.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyResourceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ApplyResourceChange',
            tfplugin6__pb2.ApplyResourceChange.Request.SerializeToString,
            tfplugin6__pb2.ApplyResourceChange.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportResourceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ImportResourceState',
            tfplugin6__pb2.ImportResourceState.Request.SerializeToString,
            tfplugin6__pb2.ImportResourceState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveResourceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/MoveResourceState',
            tfplugin6__pb2.MoveResourceState.Request.SerializeToString,
            tfplugin6__pb2.MoveResourceState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadDataSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ReadDataSource',
            tfplugin6__pb2.ReadDataSource.Request.SerializeToString,
            tfplugin6__pb2.ReadDataSource.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateResourceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/GenerateResourceConfig',
            tfplugin6__pb2.GenerateResourceConfig.Request.SerializeToString,
            tfplugin6__pb2.GenerateResourceConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateEphemeralResourceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ValidateEphemeralResourceConfig',
            tfplugin6__pb2.ValidateEphemeralResourceConfig.Request.SerializeToString,
            tfplugin6__pb2.ValidateEphemeralResourceConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenEphemeralResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/OpenEphemeralResource',
            tfplugin6__pb2.OpenEphemeralResource.Request.SerializeToString,
            tfplugin6__pb2.OpenEphemeralResource.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewEphemeralResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/RenewEphemeralResource',
            tfplugin6__pb2.RenewEphemeralResource.Request.SerializeToString,
            tfplugin6__pb2.RenewEphemeralResource.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseEphemeralResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/CloseEphemeralResource',
            tfplugin6__pb2.CloseEphemeralResource.Request.SerializeToString,
            tfplugin6__pb2.CloseEphemeralResource.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tfplugin6.Provider/ListResource',
            tfplugin6__pb2.ListResource.Request.SerializeToString,
            tfplugin6__pb2.ListResource.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateListResourceConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ValidateListResourceConfig',
            tfplugin6__pb2.ValidateListResourceConfig.Request.SerializeToString,
            tfplugin6__pb2.ValidateListResourceConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFunctions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/GetFunctions',
            tfplugin6__pb2.GetFunctions.Request.SerializeToString,
            tfplugin6__pb2.GetFunctions.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/CallFunction',
            tfplugin6__pb2.CallFunction.Request.SerializeToString,
            tfplugin6__pb2.CallFunction.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateStateStoreConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ValidateStateStoreConfig',
            tfplugin6__pb2.ValidateStateStore.Request.SerializeToString,
            tfplugin6__pb2.ValidateStateStore.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureStateStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ConfigureStateStore',
            tfplugin6__pb2.ConfigureStateStore.Request.SerializeToString,
            tfplugin6__pb2.ConfigureStateStore.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadStateBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tfplugin6.Provider/ReadStateBytes',
            tfplugin6__pb2.ReadStateBytes.Request.SerializeToString,
            tfplugin6__pb2.ReadStateBytes.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteStateBytes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/tfplugin6.Provider/WriteStateBytes',
            tfplugin6__pb2.WriteStateBytes.RequestChunk.SerializeToString,
            tfplugin6__pb2.WriteStateBytes.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/LockState',
            tfplugin6__pb2.LockState.Request.SerializeToString,
            tfplugin6__pb2.LockState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/UnlockState',
            tfplugin6__pb2.UnlockState.Request.SerializeToString,
            tfplugin6__pb2.UnlockState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/GetStates',
            tfplugin6__pb2.GetStates.Request.SerializeToString,
            tfplugin6__pb2.GetStates.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/DeleteState',
            tfplugin6__pb2.DeleteState.Request.SerializeToString,
            tfplugin6__pb2.DeleteState.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/PlanAction',
            tfplugin6__pb2.PlanAction.Request.SerializeToString,
            tfplugin6__pb2.PlanAction.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tfplugin6.Provider/InvokeAction',
            tfplugin6__pb2.InvokeAction.Request.SerializeToString,
            tfplugin6__pb2.InvokeAction.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateActionConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/ValidateActionConfig',
            tfplugin6__pb2.ValidateActionConfig.Request.SerializeToString,
            tfplugin6__pb2.ValidateActionConfig.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tfplugin6.Provider/StopProvider',
            tfplugin6__pb2.StopProvider.Request.SerializeToString,
            tfplugin6__pb2.StopProvider.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

# 🐍🏗️🔚
